name: Publish Docker Image
env:
  IMAGE_TAG: idiet.tracking
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: "${{ toJson(github) }}"
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          if: github.even.action == 'closed'
          name: docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_TAG }}
          username: johnhoman
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
