name: Publish Docker Image
env:
  IMAGE_TAG: idiet.tracking
on:
  push:
    tags:
      - v2020.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_TAG }}
          username: johnhoman
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
